server:
  port: 8761
spring:  application:    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: false
# Log Output to a file
logging:
  file:
    path: "${user.dir}/${spring.application.name}}/log/"
    name: "${spring.application.name}.log"